const properties=[
 {id:1,title:'Sunlit bedsitter near TRM',town:'Nairobi',area:'Roysambu',type:'Bedsitter',price:12500,size:'28 sq m',bath:'1 bath',verified:true,image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80'},
 {id:2,title:'Modern one bedroom apartment',town:'Nairobi',area:'Kilimani',type:'1 Bedroom',price:38000,size:'54 sq m',bath:'1 bath',verified:true,image:'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80'},
 {id:3,title:'Spacious two bedroom maisonette',town:'Kiambu',area:'Ruaka',type:'2 Bedroom',price:32000,size:'86 sq m',bath:'2 baths',verified:true,image:'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80'},
 {id:4,title:'Coastal two bedroom home',town:'Mombasa',area:'Nyali',type:'2 Bedroom',price:45000,size:'92 sq m',bath:'2 baths',verified:true,image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80'},
 {id:5,title:'Quiet one bedroom flat',town:'Nakuru',area:'Section 58',type:'1 Bedroom',price:18000,size:'48 sq m',bath:'1 bath',verified:true,image:'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=80'},
 {id:6,title:'Family three bedroom apartment',town:'Kisumu',area:'Milimani',type:'3 Bedroom',price:42000,size:'118 sq m',bath:'2 baths',verified:true,image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80'}
];
const grid=document.querySelector('#propertyGrid'),empty=document.querySelector('#emptyState'),count=document.querySelector('#resultCount'),modal=document.querySelector('#modal'),content=document.querySelector('#modalContent'),toast=document.querySelector('#toast');
const money=n=>'KSh '+n.toLocaleString('en-KE');
function render(items){grid.innerHTML=items.map(p=>`<article class="property" data-id="${p.id}" tabindex="0"><div class="photo" style="background-image:url('${p.image}')"><span class="badge">VERIFIED</span><button class="heart" aria-label="Save property">Save</button></div><div class="property-body"><span class="location">${p.area}, ${p.town}</span><h3>${p.title}</h3><div class="facts"><span>${p.type}</span><span>${p.bath}</span><span>${p.size}</span></div><div class="price">${money(p.price)} <small>/ month</small></div></div></article>`).join('');count.textContent=`${items.length} verified home${items.length===1?'':'s'}`;empty.hidden=items.length>0}
function filter(){const town=document.querySelector('#townFilter').value,type=document.querySelector('#typeFilter').value,max=+document.querySelector('#priceFilter').value;render(properties.filter(p=>(town==='all'||p.town===town)&&(type==='all'||p.type===type)&&p.price<=max))}
function propertyModal(p){content.innerHTML=`<div class="modal-photo" style="background-image:url('${p.image}')"></div><div class="modal-inner"><span class="eyebrow">Verified vacancy</span><h2>${p.title}</h2><p>${p.area}, ${p.town} - ${p.type} - ${p.bath} - ${p.size}</p><div class="modal-price">${money(p.price)} <small>/ month</small></div><div class="unlock-box"><strong>Unlock owner contact - KSh 100</strong><span>Pay securely with M-Pesa. This demo does not process a real charge.</span></div><form class="modal-form" id="unlockForm"><label>M-Pesa phone number<input type="tel" required placeholder="07XX XXX XXX" pattern="(?:\\+254|0)[17]\\d{8}"></label><button class="button" type="submit">Continue to M-Pesa</button><div class="fineprint">Never send a deposit before viewing and confirming the property.</div></form></div>`;modal.showModal()}
function genericModal(kind){const templates={signin:`<div class="modal-inner"><span class="eyebrow">Welcome back</span><h2>Sign in to NyumbaPap</h2><p>Save homes, view your unlocks, and manage your listings.</p><form class="modal-form demo-form"><label>Phone number<input required placeholder="07XX XXX XXX"></label><label>PIN<input type="password" required placeholder="****"></label><button class="button">Sign in</button><div class="fineprint">Demo only - no account is created.</div></form></div>`,list:`<div class="modal-inner"><span class="eyebrow">Property owners</span><h2>List a vacant home</h2><p>Submit the essentials now. Our verification team would review the property before publication.</p><form class="modal-form demo-form"><label>Property town<select><option>Nairobi</option><option>Kiambu</option><option>Mombasa</option><option>Nakuru</option><option>Kisumu</option></select></label><label>House type<select><option>Bedsitter</option><option>1 Bedroom</option><option>2 Bedroom</option><option>3 Bedroom</option></select></label><label>Monthly rent<input type="number" required placeholder="e.g. 25000"></label><label>Phone number<input required placeholder="07XX XXX XXX"></label><button class="button">Save draft listing</button><div class="fineprint">Publishing fee shown after verification. No charge in this demo.</div></form></div>`,safety:`<div class="modal-inner"><span class="eyebrow">Tenant protection</span><h2>Five rules for a safer move</h2><p>View the property in person.<br>Confirm the owner or authorised agent's identity.<br>Never pay a deposit before viewing.<br>Use traceable payments and obtain a receipt.<br>Report suspicious listings immediately.</p><button class="button" onclick="document.querySelector('#modal').close()">I understand</button></div>`};content.innerHTML=templates[kind];modal.showModal()}
document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();filter();document.querySelector('#homes').scrollIntoView()});
document.querySelector('#quickFilters').addEventListener('click',e=>{if(!e.target.matches('.chip'))return;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');document.querySelector('#typeFilter').value=e.target.dataset.type;filter()});
grid.addEventListener('click',e=>{if(e.target.matches('.heart')){e.stopPropagation();e.target.classList.toggle('saved');e.target.textContent=e.target.classList.contains('saved')?'Saved':'Save';showToast(e.target.classList.contains('saved')?'Home saved':'Home removed');return}const card=e.target.closest('.property');if(card)propertyModal(properties.find(p=>p.id===+card.dataset.id))});
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>genericModal(b.dataset.open)));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#'+b.dataset.scroll).scrollIntoView()));
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
document.addEventListener('submit',e=>{if(e.target.id==='unlockForm'||e.target.classList.contains('demo-form')){e.preventDefault();modal.close();showToast(e.target.id==='unlockForm'?'M-Pesa prompt simulated - no charge made':'Saved in demo mode')}});
function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}render(properties);
