import { useLocalSearchParams, router } from "expo-router";
import { useQuery } from "@tanstack/react-query";
import { Image, StyleSheet, Text, View } from "react-native";
import { absoluteMediaUrl, apiJson } from "@/lib/api";
import type { ListingDetail } from "@/lib/types";
import { ListingUnlock } from "@/components/listing-unlock";
import { Body, Button, Card, Eyebrow, H1, H2, Screen } from "@/components/ui";
import { colors, radii, spacing, typography } from "../../theme";
export default function ListingScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const query = useQuery({ queryKey: ["listing", id], queryFn: () => apiJson<{ listing: ListingDetail }>(`listings/${id}`), enabled: Boolean(id) }); if (query.isLoading) return <Screen><Body muted>Loading listing…</Body></Screen>; if (!query.data) return <Screen><H2>Listing unavailable</H2><Body muted>{query.error instanceof Error ? query.error.message : "Could not load listing"}</Body><Button secondary title="Back to listings" onPress={() => router.back()} /></Screen>; const listing = query.data.listing; const amenities = Array.isArray(listing.unit.amenities) ? listing.unit.amenities.filter(value => typeof value === "string") : []; return <Screen><Button secondary title="Back to listings" onPress={() => router.back()} /><Eyebrow>Public listing</Eyebrow>{listing.landlordBadge ? <Text style={[s.landlordBadge, listing.landlordBadge.state === "unverified" && s.unverifiedBadge]}>{listing.landlordBadge.label}</Text> : null}<H1>{listing.title}</H1><Body muted>{listing.unit.property.approximateArea}, {listing.unit.property.town}, {listing.unit.property.county}</Body><Card><Text style={s.price}>KSh {listing.unit.monthlyRentKes.toLocaleString("en-KE")}</Text><Body muted>per month</Body></Card>{listing.images.length ? listing.images.map(image => <Image key={image.id} source={{ uri: absoluteMediaUrl(image.url)! }} style={s.image} accessibilityLabel={`Interior of ${listing.title}`} />) : <Card><Body muted>No interior images have been uploaded yet.</Body></Card>}<Card><H2>About this home</H2><Body muted>{listing.description}</Body>{amenities.length ? <Body><Text style={s.bold}>Amenities:</Text> {amenities.join(", ")}</Body> : null}</Card><Card><H2>Property facts</H2><Body>{listing.unit.unitType}</Body><Body>{listing.unit.bedrooms} bedroom{listing.unit.bedrooms === 1 ? "" : "s"}</Body><Body>{listing.unit.bathrooms} bathroom{listing.unit.bathrooms === 1 ? "" : "s"}</Body>{listing.unit.sizeSquareMetres ? <Body>{listing.unit.sizeSquareMetres} square metres</Body> : null}{listing.unit.depositKes !== null ? <Body>Deposit: KSh {listing.unit.depositKes.toLocaleString("en-KE")}</Body> : null}<View style={s.unlock}><ListingUnlock listingId={listing.id} feeKes={listing.unlockFeeKes} initiallyUnlocked={listing.hasPaidUnlock} /></View></Card></Screen>; }
const s = StyleSheet.create({ image: { width: "100%", height: 230, borderRadius: radii.card, backgroundColor: "#dfe7e2" }, landlordBadge: { alignSelf: "flex-start", borderRadius: radii.pill, paddingHorizontal: 10, paddingVertical: 6, fontSize: 11, color: colors.green, backgroundColor: colors.paleGreen, fontFamily: typography.bodyBold }, unverifiedBadge: { color: "#7a4b00", backgroundColor: "#fff1d6", borderWidth: 1, borderColor: "#e7c47c" }, price: { color: colors.green, fontFamily: typography.heading, fontSize: 25 }, bold: { fontFamily: typography.bodyBold }, unlock: { marginTop: spacing.sm, paddingTop: 18, borderTopWidth: 1, borderTopColor: colors.portalLine } });
