import { useEffect, useState } from "react";
import { router } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { apiJson, saveSession } from "@/lib/api";
import { Body, Button, ErrorText, Field } from "./ui";
import { colors, spacing, typography } from "../../theme";
import { useAuth } from "@/providers/app-provider";

type Mode = "LOGIN" | "REGISTER";
export function AuthForm({ mode, initialEmail = "" }: { mode: Mode; initialEmail?: string }) {
  const auth = useAuth(); const [email, setEmail] = useState(initialEmail); const [name, setName] = useState(""); const [role, setRole] = useState<"CLIENT" | "LANDLORD" | "AGENT">("CLIENT"); const [requested, setRequested] = useState(false); const [code, setCode] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [cooldown, setCooldown] = useState(0);
  useEffect(() => { if (!cooldown) return; const timer = setInterval(() => setCooldown(value => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [cooldown > 0]);
  async function send() { const normalized = email.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized)) return setError("Enter a valid email address"); setBusy(true); setError(""); try { const body = mode === "LOGIN" ? { mode, email: normalized } : { mode, email: normalized, displayName: name, role }; const result = await apiJson<{ message: string; cooldownSeconds: number; registrationRequired?: boolean; loginRequired?: boolean }>("auth/otp/request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (mode === "LOGIN" && result.registrationRequired) { router.replace({ pathname: "/register", params: { email: normalized } }); return; } if (mode === "REGISTER" && result.loginRequired) { router.replace({ pathname: "/login", params: { email: normalized } }); return; } setEmail(normalized); setNotice(result.message); setCooldown(result.cooldownSeconds || 300); setRequested(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not send code"); } finally { setBusy(false); } }
  async function verify() { if (!/^\d{6}$/.test(code)) return setError("Enter the six-digit code"); setBusy(true); setError(""); try { const result = await apiJson<{ sessionToken: string }>("auth/otp/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, code }) }); if (!result.sessionToken) throw new Error("The backend did not return a mobile session"); await saveSession(result.sessionToken); await auth.refresh(); router.replace("/(tabs)/dashboard"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not verify code"); } finally { setBusy(false); } }
  if (requested) return <View style={styles.form}><Body muted>Enter the six-digit code sent to {email}. It expires in five minutes.</Body><Body muted>{mode === "LOGIN" ? "This code signs you in to your existing account." : "If this email already belongs to an account, sign in instead."}</Body>{notice ? <Text style={styles.notice}>{notice}</Text> : null}<Field label="Verification code" value={code} onChangeText={value => setCode(value.replace(/\D/g, "").slice(0, 6))} keyboardType="number-pad" textContentType="oneTimeCode" autoFocus /><ErrorText message={error} /><Button title="Verify and continue" busy={busy} onPress={verify} /><Button secondary disabled={busy || cooldown > 0} title={cooldown ? `Resend available in ${Math.floor(cooldown / 60)}:${String(cooldown % 60).padStart(2, "0")}` : "Resend email"} onPress={send} /><Button secondary title="Use a different email" onPress={() => { setRequested(false); setCode(""); setError(""); }} /></View>;
  return <View style={styles.form}>{mode === "REGISTER" ? <><Field label="Full name" value={name} onChangeText={setName} autoCapitalize="words" /><Text style={styles.label}>Account type</Text><View style={styles.roles}>{(["CLIENT", "LANDLORD", "AGENT"] as const).map(value => <Text key={value} onPress={() => setRole(value)} style={[styles.role, role === value && styles.roleActive]}>{value === "CLIENT" ? "Home seeker" : value === "LANDLORD" ? "Landlord" : "Agent"}</Text>)}</View></> : null}<Field label="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email" /><ErrorText message={error} /><Button title={busy ? "Sending code..." : "Send verification code"} busy={busy} onPress={send} /></View>;
}
const styles = StyleSheet.create({ form: { gap: spacing.md, marginTop: spacing.lg }, notice: { color: colors.muted, fontFamily: typography.body, lineHeight: 22 }, label: { fontFamily: typography.bodyBold, color: colors.ink }, roles: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, role: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, borderWidth: 1, borderColor: colors.line, color: colors.muted, fontFamily: typography.bodyBold }, roleActive: { backgroundColor: colors.green, borderColor: colors.green, color: colors.white } });
