import { useState } from "react";
import * as ImagePicker from "expo-image-picker";
import { useQueryClient } from "@tanstack/react-query";
import { apiMultipart } from "@/lib/api";
import { createNativeFileFormData } from "@/lib/native-multipart";
import { Body, Button, ErrorText } from "./ui";

export function InteriorImageUpload({ listingId }: { listingId: string }) {
  const client = useQueryClient(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [uploadState, setUploadState] = useState<"IDLE" | "UPLOADING" | "FAILED" | "SUCCEEDED">("IDLE");
  async function upload() { setError(""); setMessage(""); try { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError("Photo-library access is required to select interior images."); const selection = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsMultipleSelection: true, selectionLimit: 6, quality: 1 }); if (selection.canceled) return; setBusy(true); setUploadState("UPLOADING"); const files = selection.assets.slice(0, 6).map((asset, index) => ({ uri: asset.uri, name: asset.fileName ?? `interior-${index + 1}.jpg`, mimeType: asset.mimeType ?? "image/jpeg" })); const form = createNativeFileFormData("images", files); const response = await apiMultipart(`dashboard/listings/${listingId}/images`, form); const result = await response.json().catch(() => ({})); if (!response.ok) { setUploadState("FAILED"); throw new Error(result.retryable ? "Media storage is temporarily unavailable. Your photos remain on your device; retry in a moment." : result.error ?? "Could not upload images"); } const count = Array.isArray(result.images) ? result.images.length : 0; setMessage(`${count} image${count === 1 ? "" : "s"} uploaded.`); setUploadState("SUCCEEDED"); await client.invalidateQueries({ queryKey: ["dashboard"] }); } catch (caught) { setUploadState("FAILED"); setError(caught instanceof Error ? caught.message : "Could not upload images"); } finally { setBusy(false); } }
  return <><Body muted>Interior images: up to 6 at once. JPEG, PNG, WebP, or AVIF.</Body>{uploadState === "UPLOADING" ? <Body muted>Upload pending—processing and storing your images…</Body> : null}{uploadState === "FAILED" ? <Body muted>Upload failed safely. Retry when your connection or media storage recovers.</Body> : null}<ErrorText message={error} />{message ? <Body>{message}</Body> : null}<Button secondary busy={busy} title={busy ? "Processing..." : uploadState === "FAILED" ? "Retry interior upload" : "Select and upload interiors"} onPress={upload} /></>;
}
