import { useEffect, useState } from "react";
import { router } from "expo-router";
import { Modal, StyleSheet, Text, View } from "react-native";
import MapView, { Marker } from "react-native-maps";
import { apiJson } from "@/lib/api";
import { useAuth } from "@/providers/app-provider";
import { Body, Button, Card, ErrorText, Field, H2 } from "./ui";
import { colors, radii, shadows, spacing, typography } from "../../theme";

type UiState = "IDLE" | "WAITING" | "PAID" | "CANCELLED" | "WRONG_PIN" | "INSUFFICIENT_FUNDS" | "TIMED_OUT" | "FAILED";
type Reveal = { contact: string; contactName: string; exactCoordinates: { latitude: number; longitude: number } };
const copy: Record<Exclude<UiState, "IDLE" | "PAID">, string> = { WAITING: "Check your phone and enter your M-Pesa PIN.", CANCELLED: "You cancelled the STK request. You can retry when ready.", WRONG_PIN: "The M-Pesa PIN was incorrect. Check it and retry.", INSUFFICIENT_FUNDS: "The M-Pesa account has insufficient funds. Use another number or add funds, then retry.", TIMED_OUT: "The STK request expired without a response. Please retry.", FAILED: "M-Pesa could not complete this request. Please retry." };

export function ListingUnlock({ listingId, feeKes, initiallyUnlocked }: { listingId: string; feeKes: number; initiallyUnlocked: boolean }) {
  const auth = useAuth(); const [open, setOpen] = useState(false); const [phone, setPhone] = useState(auth.session?.phone?.replace(/^\+/, "") ?? ""); const [paymentId, setPaymentId] = useState<string | null>(null); const [state, setState] = useState<UiState>(initiallyUnlocked ? "PAID" : "IDLE"); const [error, setError] = useState(""); const [reveal, setReveal] = useState<Reveal | null>(null);
  async function loadReveal() { try { setReveal(await apiJson<Reveal>(`listings/${listingId}/contact`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not reveal contact"); } }
  useEffect(() => { if (initiallyUnlocked) void loadReveal(); }, [initiallyUnlocked]);
  useEffect(() => { if (!paymentId || state !== "WAITING") return; const started = Date.now(); const timer = setInterval(async () => { try { const result = await apiJson<{ payment: { uiState: UiState } }>(`payments/${paymentId}/status`); if (result.payment.uiState !== "WAITING") { clearInterval(timer); setState(result.payment.uiState); if (result.payment.uiState === "PAID") await loadReveal(); } else if (Date.now() - started >= 90_000) { clearInterval(timer); setState("TIMED_OUT"); } } catch {} }, 3000); return () => clearInterval(timer); }, [paymentId, state]);
  async function pay() { if (!/^254[17]\d{8}$/.test(phone)) return setError("Enter a Safaricom number in the format 2547XXXXXXXX or 2541XXXXXXXX"); setError(""); try { const result = await apiJson<{ payment: { id: string } }>("payments/mpesa/stk-push", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ listingId, phoneE164: phone }) }); setPaymentId(result.payment.id); setState("WAITING"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not start M-Pesa payment"); } }
  if (reveal) return <Card><Text style={s.eyebrow}>Unlocked</Text><H2>Contact and exact location</H2><Body>{reveal.contactName}{"\n"}{reveal.contact}</Body><MapView style={s.map} initialRegion={{ ...reveal.exactCoordinates, latitudeDelta: 0.008, longitudeDelta: 0.008 }}><Marker coordinate={reveal.exactCoordinates} pinColor={colors.orange} /></MapView></Card>;
  if (!auth.session) return <Button title={`Unlock contact & exact location — KES ${feeKes.toLocaleString("en-KE")}`} onPress={() => router.push("/login")} />;
  return <><Button title={`Unlock contact & exact location — KES ${feeKes.toLocaleString("en-KE")}`} onPress={() => setOpen(true)} /><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><View style={s.backdrop}><View style={s.panel}><Text onPress={() => setOpen(false)} style={s.close}>×</Text><H2>Unlock this listing</H2><Body muted>One-time fee: KES {feeKes.toLocaleString("en-KE")}</Body><Field label="Safaricom phone number" value={phone} onChangeText={value => setPhone(value.replace(/\D/g, ""))} keyboardType="phone-pad" placeholder="2547XXXXXXXX" editable={state !== "WAITING"} />{state !== "IDLE" && state !== "PAID" ? <Body muted>{copy[state]}</Body> : null}<ErrorText message={error} />{state !== "WAITING" && state !== "PAID" ? <Button title={state === "IDLE" ? "Send STK push" : "Retry payment"} onPress={pay} /> : null}</View></View></Modal></>;
}
const s = StyleSheet.create({ eyebrow: { color: colors.eyebrow, fontFamily: typography.bodyBold, textTransform: "uppercase", letterSpacing: 1.6 }, map: { height: 360, borderRadius: radii.card }, backdrop: { flex: 1, backgroundColor: "rgba(8,35,29,.72)", padding: 16, justifyContent: "center" }, panel: { position: "relative", backgroundColor: colors.white, borderRadius: radii.panel, padding: 28, gap: spacing.md, ...shadows.modal }, close: { position: "absolute", right: 18, top: 8, zIndex: 2, color: colors.muted, fontSize: 32, fontFamily: typography.body }, });
