import { describe, expect, it, vi } from "vitest";
import { processDarajaCallback } from "@/modules/payments/process-callback";
const payload = (code = 0, amount = 100) => JSON.stringify({ Body: { stkCallback: { MerchantRequestID: "merchant-1", CheckoutRequestID: "checkout-1", ResultCode: code, ResultDesc: "done", CallbackMetadata: { Item: [{ Name: "Amount", Value: amount }, { Name: "MpesaReceiptNumber", Value: "RCPT123" }] } } } });
function fakeDb(state: "PENDING" | "PAID" = "PENDING") { const unlock = vi.fn(); const update = vi.fn(); const payment = { id: "p1", userId: "u1", listingId: "l1", purpose: "TENANT_UNLOCK", amountKes: 100, state, merchantRequestId: "merchant-1" }; return { unlock, update, db: { $transaction: async (fn: (tx: unknown) => unknown) => fn({ payment: { findUnique: vi.fn().mockResolvedValue(payment), update }, tenantUnlock: { upsert: unlock } }) } }; }
describe("Daraja callback entitlement", () => {
  it("creates an unlock only after verified success and matching amount", async () => { const fake = fakeDb(); await processDarajaCallback(fake.db as never, payload()); expect(fake.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ state: "PAID", providerReceipt: "RCPT123" }) })); expect(fake.unlock).toHaveBeenCalledOnce(); });
  it("does not unlock a failed callback", async () => { const fake = fakeDb(); await processDarajaCallback(fake.db as never, payload(1032)); expect(fake.unlock).not.toHaveBeenCalled(); expect(fake.update).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ state: "FAILED" }) })); });
  it("rejects a callback with a mismatched amount", async () => { const fake = fakeDb(); await expect(processDarajaCallback(fake.db as never, payload(0, 1))).rejects.toThrow("INVALID_PAYMENT_CONFIRMATION"); expect(fake.unlock).not.toHaveBeenCalled(); });
  it("is idempotent once paid", async () => { const fake = fakeDb("PAID"); const result = await processDarajaCallback(fake.db as never, payload()); expect(result.duplicate).toBe(true); expect(fake.update).not.toHaveBeenCalled(); expect(fake.unlock).not.toHaveBeenCalled(); });
});
